### ISSUE TITLE
How I can add my sheet_metal dir. to train and inference

### ISSUE THREAD

**Issue by qin53027** [byungjae89/SPADE-pytorch#11]
This is Jimmy from Nvidia. This PM I spent some time on your website: https://github.com/byungjae89/SPADE-pytorch which is very good.
 
Then I try to add my simple dataset for sheet metal defect in the mvtec.py after I put the sheet_metal inside the data dir.

My sheet_metal fold has 33 png in train dir. while it has 10 mask file in the ground_truth dir and 10 test files in the test dir.
 
In the attached small dataset, I have deleted the train dir. to reduce the size.
 
But after I have run: python3 main.py, I have got following error when starting to train the sheet_metal.
 
raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
 
Could you please advise what I have missed?
 
Thanks so much
Jimmy

**Comment by FirokOtaku** [comment]
Same issue when trying to train/inference on custom dataset and giving some hacks on `main.py`/`datasets/mvtec.py`.

```
(SPADE-pytorch) T:\Projects\SPADE-pytorch\src>python main.py
device used: cuda
| feature extraction | train | water |: 100%|██████████████████████████████████████████████████████████████████████████████| 10/10 [00:16<00:00,  1.64s/it]
C:\Users\firok\.conda\envs\SPADE-pytorch\lib\site-packages\torch\storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
| feature extraction | test | water |: 100%|█████████████████████████████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.56s/it]
C:\Users\firok\.conda\envs\SPADE-pytorch\lib\site-packages\sklearn\metrics\_ranking.py:943: UndefinedMetricWarning: No negative samples in y_true, false positive value should be meaningless
  UndefinedMetricWarning)
Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 126, in main
    roc_auc = roc_auc_score(gt_list, scores)
  File "C:\Users\firok\.conda\envs\SPADE-pytorch\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\firok\.conda\envs\SPADE-pytorch\lib\site-packages\sklearn\metrics\_ranking.py", line 545, in roc_auc_score
    sample_weight=sample_weight)
  File "C:\Users\firok\.conda\envs\SPADE-pytorch\lib\site-packages\sklearn\metrics\_base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "C:\Users\firok\.conda\envs\SPADE-pytorch\lib\site-packages\sklearn\metrics\_ranking.py", line 327, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
```

How to reproduce:

```bash
conda create -n SPADE-pytorch python=3.6 -y
conda activate SPADE-pytorch
conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.2 -c pytorch -y
conda install matplotlib -y
pip install sklearn tqdm
cd src
python main.py
```

Modified script files:

`main.py #32`

```python
# device setup
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('device used: ' + device)

# load model
model = wide_resnet50_2(pretrained=False, progress=True)
checkpoint: dict = torch.load('../data/wide_resnet50_2-95faca4d.pth', map_location=device) # use manually downloaded checkpoint file
model.load_state_dict(checkpoint)
model.to(device)
model.eval()
```

`main.py #60`

```python
mvtec.CLASS_NAMES.clear()
mvtec.CLASS_NAMES.append('water') # use customized dataset name

for class_name in mvtec.CLASS_NAMES:

  train_dataset = mvtec.MVTecDataset(root_path='./dataset', class_name=class_name, is_train=True) # use customized folder path
  train_dataloader = DataLoader(train_dataset, batch_size=32, pin_memory=True)
  test_dataset = mvtec.MVTecDataset(root_path='./dataset', class_name=class_name, is_train=False) # use customized folder path
  test_dataloader = DataLoader(test_dataset, batch_size=32, pin_memory=True)
```

`datasets/mvtec.py #27`

```python
self.mvtec_folder_path = root_path # remove join call
```
